### ISSUE TITLE
the file param.json is missing

### ISSUE THREAD

**Issue by bimthinker** [CCWI/EP-Room-Simulator#1]
when running the app and using the example file(idf,epw), in step2, get the following error: 

FileNotFoundError: [Errno 2] No such file or directory: './meta_data/param.json'

I search in the folder and the file is not found.

**Comment by bimthinker** [comment]
after create the meta_data folder, the issue is solved.

**Comment by weberml** [comment]
Thank you very much for this hint. We added the folder and temporary files.
Please let us know if there are any other problems with running the application.
